// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijjawnbezcdqxuyhbbpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqamF3bmJlemNkcXh1eWhiYnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTEwNjgsImV4cCI6MjA2MTg2NzA2OH0.QHCQxzLcgYd0-OeNjKaAB29QjrYxf4e9qFGk60C0SuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);