name: Lint & Type-Check

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run lint
      - name: Run TypeScript type-check
        run: pnpm run typecheck
